---
title: "World Bank data exploration"
author: "Saif Shabou"
date: "17/02/2021"
output:
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 10
    fig_height: 5
# output:
#   html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



In this notebook wi will explore ghg emissions data published from world bank. 

# Get data


Let's identify datasets related to ghg emissions

```{r}
library(WDI)
new_wdi_cache <- WDIcache()
datasets = WDIsearch("*emissions.", cache = new_wdi_cache)
print(head(datasets))
```


# Total GHG emissions

```{r}
data = WDI(indicator=c("wb_total_ghg_emissions" = "EN.ATM.GHGT.KT.CE"))

print(head(datasets))
```

## Plot

```{r}

library(dplyr)
emission_FR <- data %>% filter(iso2c == "FR")
emission_USA <- data %>% filter(iso2c == "US")

# non interactive plot
library(ggplot2)
ggplot(emission_FR, 
       aes(year, wb_total_ghg_emissions, color=country)) + 
  geom_line() + 
  xlab('Year') + 
  ylab('GDP per capita')

# interactive plot

# library(plotly)
# 
# fig <- plot_ly(emission_FR, x = ~year, y = ~wb_total_ghg_emissions,
#                type = 'scatter', mode = 'lines')
# 
# fig
```

# References
- rendering [github_document](https://rmarkdown.rstudio.com/github_document_format.html)
